version: '3.4'

services:
  firstapi:
    image: ${DOCKER_REGISTRY-}firstapi
    build:
      context: .
      dockerfile: FirstApi/Dockerfile

  reservationdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Esed2003@
  seconcdapi:
    image: ${DOCKER_REGISTRY-}seconcdapi
    build:
      context: .
      dockerfile: SeconcdApi/Dockerfile

