version: '3.4'

services:
  envoygateway:
    build: 
      context: .
      dockerfile: ./Envoy/Dockerfile
  firstapi:
    image: ${DOCKER_REGISTRY-}firstapi
    build:
      context: .
      dockerfile: FirstApi/Dockerfile
  reservationdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
  secondapi:
    image: ${DOCKER_REGISTRY-}secondapi
    build:
      context: .
      dockerfile: SeconcdApi/Dockerfile
  rabbitmq:
    image: rabbitmq:3.12.2-management
  web:
    image: ${DOCKER_REGISTRY-}web
    build:
      context: .
      dockerfile: Web/Dockerfile
    
      
    

